### ISSUE TITLE
Improve Thread-ID

### ISSUE THREAD

**Issue by ccare** [meducation/filum#6]
Our desire with Filum is to have readable logs (with columnar padding) to this end, I propose that we modify the thread_id column.

On my system this is currently reading as:

```
thread_id-7626360
```

The duplicate text is taking up 10 chars and the actual id can be different lengths (I've seen 7-8 digits). I therefore propose we switch to 

```
t-7626360
```

And pad to 10 or 11 chars

**Comment by iHiD** [comment]
@ccare++
